"""Video AI subsystem exception module exports."""

from app.video.exceptions.video_exceptions import (
    VideoError,
    VideoException,
    ConfigurationError,
    DatasetError,
    DatasetNotFoundError,
    DatasetNotFound,
    ProtocolParsingError,
    CorruptVideoFileError,
    PreprocessingError,
    FrameExtractionError,
    FaceDetectionError,
    FaceAlignmentError,
    AugmentationError,
    ModelError,
    ModelNotFoundError,
    ModelInitializationError,
    ModelCheckpointError,
    CheckpointError,
    TrainingError,
    PipelineError,
    RegistryError,
    ComponentNotFoundError,
    DuplicateRegistrationError,
)

__all__ = [
    "VideoError",
    "VideoException",
    "ConfigurationError",
    "DatasetError",
    "DatasetNotFoundError",
    "DatasetNotFound",
    "ProtocolParsingError",
    "CorruptVideoFileError",
    "PreprocessingError",
    "FrameExtractionError",
    "FaceDetectionError",
    "FaceAlignmentError",
    "AugmentationError",
    "ModelError",
    "ModelNotFoundError",
    "ModelInitializationError",
    "ModelCheckpointError",
    "CheckpointError",
    "TrainingError",
    "PipelineError",
    "RegistryError",
    "ComponentNotFoundError",
    "DuplicateRegistrationError",
]
