"use client";

import { useEffect, useState, useMemo, use } from "react";
import { useRouter } from "next/navigation";
import { motion } from "framer-motion";
import {
  ArrowLeft,
  Hash,
  Clock,
  FileText,
  FileCode,
  Download,
  Copy,
  Check,
} from "lucide-react";
import Navbar from "../../../components/Navbar";
import VerdictGauge from "../../../components/VerdictGauge";
import MediaInspector from "../../../components/MediaInspector";
import EvidenceMatrix from "../../../components/EvidenceMatrix";
import ForensicNarrative from "../../../components/ForensicNarrative";
import Footer from "../../../components/Footer";
import { ScanSession, ConsolidatedForensicReport } from "../../../lib/types";

interface ReportPageProps {
  params: Promise<{ scanId: string }>;
}

export default function ReportPage({ params }: ReportPageProps) {
  const { scanId } = use(params);
  const router = useRouter();
  const [session, setSession] = useState<ScanSession | null>(null);
  const [file, setFile] = useState<File | null>(null);
  const [copied, setCopied] = useState(false);

  // Load session data from sessionStorage
  useEffect(() => {
    const raw = sessionStorage.getItem(`scan_${scanId}`);
    if (raw) {
      try {
        const parsed: ScanSession = JSON.parse(raw);
        setSession(parsed);
      } catch {
        // Invalid data
      }
    }

    // Reconstruct File from stored base64
    const fileRaw = sessionStorage.getItem(`scan_file_${scanId}`);
    if (fileRaw) {
      try {
        const fileData = JSON.parse(fileRaw);
        fetch(fileData.data)
          .then((res) => res.blob())
          .then((blob) => {
            const reconstructedFile = new File([blob], fileData.name, {
              type: fileData.type,
            });
            setFile(reconstructedFile);
          });
      } catch {
        // File reconstruction failed
      }
    }
  }, [scanId]);

  const report: ConsolidatedForensicReport | null = session?.report ?? null;

  const formattedTimestamp = useMemo(() => {
    if (!session?.timestamp) return "";
    const date = new Date(session.timestamp);
    return date.toLocaleString("en-US", {
      year: "numeric",
      month: "short",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
      second: "2-digit",
    });
  }, [session?.timestamp]);

  const handleCopyScanId = () => {
    navigator.clipboard.writeText(scanId);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadMarkdown = () => {
    if (!report) return;
    const nl = report.natural_language_report;
    const confidencePct = Math.round(report.overall_confidence * 100);

    const content = `# DeepGuard Forensic Investigation Report

**Scan ID:** ${scanId}
**Verdict:** ${report.verdict} (${confidencePct}%)
**Media Type:** ${report.media_type}
**Processing Time:** ${report.processing_time_ms.toFixed(0)} ms
**Timestamp:** ${formattedTimestamp}

---

## Executive Summary
${nl?.executive_summary || "Telemetry compiled without generative narrative."}

## Visual Analysis
${nl?.visual_analysis_narrative || "N/A"}

## Audio Analysis
${nl?.audio_analysis_narrative || "N/A"}

## Temporal Inconsistency Notes
${nl?.temporal_inconsistency_notes || "N/A"}

## Forensic Recommendations
${nl?.forensic_recommendations?.map((r: string) => "- " + r).join("\n") || "N/A"}

---
*Generated by DeepGuard Forensics Platform*
`;

    const blob = new Blob([content], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `forensic_report_${scanId}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadJson = () => {
    if (!report) return;
    const jsonStr = JSON.stringify(
      { scanId, timestamp: session?.timestamp, ...report },
      null,
      2
    );
    const blob = new Blob([jsonStr], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `forensic_certificate_${scanId}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  // Loading / Not Found
  if (!session || !report) {
    return (
      <main className="min-h-screen bg-[#07080f] text-[#e8eaed]">
        <Navbar />
        <div className="flex flex-col items-center justify-center min-h-[60vh] gap-4">
          <div className="glass-card p-10 text-center space-y-4 max-w-md">
            <Hash className="h-12 w-12 text-[#6b7280] mx-auto" />
            <h2 className="text-xl font-bold text-white">Scan Not Found</h2>
            <p className="text-sm text-[#6b7280]">
              This scan session has expired or does not exist. Please run a new
              forensic scan from the home page.
            </p>
            <button
              onClick={() => router.push("/")}
              className="inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-[#38bdf8] to-[#6366f1] px-6 py-2.5 text-sm font-bold text-white"
            >
              <ArrowLeft className="h-4 w-4" />
              Return to Scanner
            </button>
          </div>
        </div>
      </main>
    );
  }

  return (
    <main className="min-h-screen bg-[#07080f] text-[#e8eaed]">
      {/* Background */}
      <div className="pointer-events-none fixed inset-0 z-0 cyber-dots opacity-30" />

      <Navbar />

      <div className="relative z-10 mx-auto max-w-7xl px-6 py-8 space-y-6">
        {/* ═══════════════════════════════════════════════════════════
            TOP AUDIT BAR
            ═══════════════════════════════════════════════════════════ */}
        <motion.div
          initial={{ opacity: 0, y: -10 }}
          animate={{ opacity: 1, y: 0 }}
          className="glass-panel px-5 py-3 flex flex-col md:flex-row items-start md:items-center justify-between gap-4"
        >
          {/* Left: Back + Metadata */}
          <div className="flex items-center gap-4 flex-wrap">
            <button
              onClick={() => router.push("/")}
              className="flex items-center gap-1.5 rounded-lg border border-white/[0.06] bg-white/[0.02] px-3 py-1.5 text-xs font-medium text-[#9ca3af] hover:text-white hover:border-white/[0.12] transition"
            >
              <ArrowLeft className="h-3.5 w-3.5" />
              Return to Scanner
            </button>

            <div className="flex items-center gap-2 text-xs font-mono">
              <button
                onClick={handleCopyScanId}
                className="flex items-center gap-1.5 rounded-lg bg-white/[0.04] border border-white/[0.06] px-2.5 py-1 text-[#38bdf8] hover:bg-white/[0.06] transition"
              >
                <Hash className="h-3 w-3" />
                {scanId}
                {copied ? (
                  <Check className="h-3 w-3 text-[#10b981]" />
                ) : (
                  <Copy className="h-3 w-3 opacity-50" />
                )}
              </button>

              <span className="flex items-center gap-1 text-[#6b7280]">
                <Clock className="h-3 w-3" />
                {formattedTimestamp}
              </span>
            </div>
          </div>

          {/* Right: Export Actions */}
          <div className="flex items-center gap-2">
            <button
              onClick={handleDownloadMarkdown}
              className="flex items-center gap-1.5 rounded-lg border border-white/[0.06] bg-white/[0.03] px-3 py-1.5 text-xs font-medium text-[#9ca3af] hover:text-white hover:border-[#38bdf8]/30 transition"
            >
              <FileText className="h-3.5 w-3.5 text-[#38bdf8]" />
              Export PDF
            </button>
            <button
              onClick={handleDownloadJson}
              className="flex items-center gap-1.5 rounded-lg border border-white/[0.06] bg-white/[0.03] px-3 py-1.5 text-xs font-medium text-[#9ca3af] hover:text-white hover:border-[#6366f1]/30 transition"
            >
              <FileCode className="h-3.5 w-3.5 text-[#6366f1]" />
              Download JSON
            </button>
            <button
              onClick={() => {
                handleDownloadMarkdown();
                handleDownloadJson();
              }}
              className="flex items-center gap-1.5 rounded-lg bg-gradient-to-r from-[#38bdf8]/10 to-[#6366f1]/10 border border-[#38bdf8]/20 px-3 py-1.5 text-xs font-medium text-white hover:border-[#38bdf8]/40 transition"
            >
              <Download className="h-3.5 w-3.5" />
              Export All
            </button>
          </div>
        </motion.div>

        {/* ═══════════════════════════════════════════════════════════
            VERDICT & DUAL RISK GAUGE
            ═══════════════════════════════════════════════════════════ */}
        <VerdictGauge
          verdict={report.verdict}
          confidence={report.overall_confidence}
          mediaType={report.media_type}
          processingTimeMs={report.processing_time_ms}
        />

        {/* ═══════════════════════════════════════════════════════════
            MAIN CONTENT: INSPECTOR + EVIDENCE
            ═══════════════════════════════════════════════════════════ */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
          {/* Left: Media Inspector */}
          <div className="lg:col-span-7">
            <MediaInspector report={report} file={file} />
          </div>

          {/* Right: Evidence Matrix */}
          <div className="lg:col-span-5">
            <EvidenceMatrix report={report} />
          </div>
        </div>

        {/* ═══════════════════════════════════════════════════════════
            FORENSIC NARRATIVE
            ═══════════════════════════════════════════════════════════ */}
        <ForensicNarrative report={report} />
      </div>

      <Footer />
    </main>
  );
}
